name: build-test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - $default-branch
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn

      - uses: ./.github/workflows/actions/cache-app

      - run: yarn --frozen-lockfile --ignore-scripts --prefer-offline
      - run: git fetch --no-tags --prune --depth=5 origin $default-branch
      - run: yarn nx codegen api # Generate Prisma first
      - run: yarn nx run-many --target codegen --all
      - run: yarn nx affected --target test --base origin/$default-branch --parallel
      - run: yarn nx affected --target lint --base origin/$default-branch --parallel
      - run: yarn nx run-many --target build --all --prod --parallel

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn

      - uses: ./.github/workflows/actions/cache-app
      - uses: ./.github/workflows/actions/setup-docker

      - name: Run docker-compose
        run: yarn docker:api --env-file .env.ci up -d

      - run: yarn nx integration

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/cache-app
      - uses: ./.github/workflows/actions/setup-docker

      - name: Docker build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./apps/api/Dockerfile
          push: false
          tags: caster-api:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
