name: build-test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 Automatically triggered by a ${{ github.event_name }}"
      - run: echo "🔎 Running on a ${{ runner.os }} server based on ${{ github.ref }}"

      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn

      - run: yarn --frozen-lockfile --ignore-scripts --prefer-offline
      - run: git fetch --no-tags --prune --depth=1 origin main
      - run: yarn nx codegen api # Generate Prisma first
      - run: yarn nx run-many --target codegen --all
      - run: yarn nx affected --target test --base origin/main --parallel
      - run: yarn nx affected --target lint --base origin/main --parallel
      - run: yarn nx affected --target build --base origin/main --prod --parallel
